# Generated by Django 2.1.2 on 2018-11-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notregisteredpatient',
            old_name='r_cislo',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='registeredpatient',
            old_name='r_cislo',
            new_name='person_id',
        ),
    ]
