# Generated by Django 2.1.2 on 2018-11-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20181105_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notregisteredpatient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notregisteredpatient',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='registeredpatient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registeredpatient',
            name='person_id',
        ),
        migrations.AddField(
            model_name='notregisteredpatient',
            name='patient_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patients.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredpatient',
            name='patient_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patients.Patient'),
            preserve_default=False,
        ),
    ]
