# Generated by Django 2.1.2 on 2018-11-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_auto_20181123_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('workplace_city', models.CharField(max_length=50)),
                ('workplace_street', models.CharField(max_length=50)),
                ('workplace_postcode', models.CharField(max_length=5)),
                ('workplace_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('substance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='visit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.Visit'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='visit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.Visit'),
        ),
        migrations.AddField(
            model_name='examination',
            name='visit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.Visit'),
        ),
    ]
